# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-11 12:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bom',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=50, verbose_name='Model Name')),
                ('rev', models.CharField(max_length=50, verbose_name='Model Revision')),
                ('description', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BomDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pn', models.CharField(max_length=50, verbose_name='Part Number')),
                ('customer_pn', models.CharField(max_length=50, verbose_name='Customer Part number')),
                ('rd', models.CharField(max_length=50, verbose_name='Reference Destination')),
                ('description', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_details', to='production.Bom')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentControls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_number', models.CharField(db_index=True, max_length=255)),
                ('doc_type', models.CharField(choices=[('DA', 'DA'), ('ECO', 'ECO')], db_index=True, default='DA', max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('details', models.CharField(max_length=4000)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('initial_date', models.DateField(blank=True, null=True)),
                ('expire_date', models.DateField(blank=True, null=True)),
                ('finished_date', models.DateField(blank=True, null=True)),
                ('bom_process', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Opened'), ('CLOSE', 'Closed'), ('PENDING', 'Pending')], db_index=True, default='OPEN', max_length=50)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.CharField(max_length=4000)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('doc_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='production.DocumentControls')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentRelated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=50)),
                ('item_type', models.CharField(choices=[('FAMILY', 'Family'), ('PRODUCT', 'Product'), ('GOLF', 'Golf')], db_index=True, default='PRODUCT', max_length=50)),
                ('details', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('doc_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_list', to='production.DocumentControls')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('name', models.CharField(db_index=True, max_length=50, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('units', models.CharField(blank=True, max_length=50, null=True)),
                ('group', models.CharField(db_index=True, max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('activated', models.BooleanField(default=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Performing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loop', models.IntegerField(db_index=True, default=1)),
                ('started_date', models.DateTimeField(db_index=True)),
                ('finished_date', models.DateTimeField()),
                ('tester', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('result', models.BooleanField(db_index=True, default=True)),
                ('dispose_code', models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PerformingDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(blank=True, null=True)),
                ('value_str', models.CharField(blank=True, max_length=50, null=True)),
                ('limit_min', models.FloatField(blank=True, null=True)),
                ('limit_max', models.FloatField(blank=True, null=True)),
                ('value_type', models.CharField(choices=[('String', 'String'), ('Number', 'Number')], default='String', max_length=10)),
                ('result', models.BooleanField(db_index=True, default=True)),
                ('created_date', models.DateTimeField()),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performing_used', to='production.Parameter')),
                ('performing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performingdetail_list', to='production.Performing')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('model', models.CharField(db_index=True, max_length=50, verbose_name='Model Name')),
                ('rev', models.CharField(max_length=50, verbose_name='Model Revision')),
                ('customer_model', models.CharField(max_length=50, verbose_name='Customer Model')),
                ('customer_rev', models.CharField(max_length=50, verbose_name='Customer Model revision')),
                ('group', models.CharField(max_length=50, verbose_name='Product Group')),
                ('description', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('bom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_used', to='production.Bom')),
                ('family', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_used', to='production.Family')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Routing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoutingDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station', models.CharField(db_index=True, max_length=50, verbose_name='Station number')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Station name')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('process', models.CharField(blank=True, max_length=255, null=True)),
                ('first_process', models.BooleanField(default=False, verbose_name='First process station?')),
                ('last_process', models.BooleanField(default=False, verbose_name='Last process station?')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('family', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='station_used', to='production.Family')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('qty', models.IntegerField(default=1)),
                ('build_type', models.CharField(choices=[('PROD', 'Production'), ('RMA', 'Repair'), ('QUAL', 'Qualification')], default='PROD', max_length=10)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workorder_used', to='production.Product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrderDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(db_index=True, max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('result', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('IN', 'In Process'), ('DONE', 'Completed Process'), ('SHIPPED', 'Shipped')], db_index=True, default='IN', max_length=50)),
                ('current_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sn_current_station', to='production.Station')),
                ('last_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sn_last_station', to='production.Station')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sn_list', to='production.WorkOrder')),
            ],
        ),
        migrations.AddField(
            model_name='routingdetails',
            name='next_fail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_used_next_fail', to='production.Station'),
        ),
        migrations.AddField(
            model_name='routingdetails',
            name='next_pass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_used_next_pass', to='production.Station'),
        ),
        migrations.AddField(
            model_name='routingdetails',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_details', to='production.Routing'),
        ),
        migrations.AddField(
            model_name='routingdetails',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_used', to='production.Station'),
        ),
        migrations.AddField(
            model_name='routingdetails',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='performing',
            name='sn_wo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performing_list', to='production.WorkOrderDetails'),
        ),
        migrations.AddField(
            model_name='performing',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perform_station', to='production.Station'),
        ),
        migrations.AddField(
            model_name='performing',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='bom',
            unique_together=set([('model', 'rev')]),
        ),
    ]
