# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-13 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_auto_20161013_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='critical',
            field=models.BooleanField(default=False, verbose_name='Critical station?'),
        ),
        migrations.AddField(
            model_name='parameter',
            name='ordering',
            field=models.IntegerField(default=1),
        ),
    ]
