# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-27 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_auto_20161013_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='critical',
            field=models.BooleanField(default=False, verbose_name='Critical Family?'),
        ),
        migrations.AddField(
            model_name='family',
            name='ordering',
            field=models.IntegerField(default=1),
        ),
    ]
